### ISSUE TITLE
Requesting new release

### ISSUE THREAD

**Issue by sandal-maker** [wtanaka/ansible-role-gcloud-sdk#13]
Hey, noticed that there have been 4 commits since the last release. Could you create a new release capturing these new changes please?

Cheers.
@sandal-maker

**Comment by wtanaka** [comment]
Thanks for the suggestion.

https://github.com/wtanaka/ansible-role-gcloud-sdk/releases/tag/v2.0.0

**Comment by sandal-maker** [comment]
@wtanaka Thanks a bunch

**Comment by sandal-maker** [comment]
@wtanaka One more thing, could you make v2.0.0 available in Ansible Galaxy as well please?

**Comment by wtanaka** [comment]
2.0.1 in Galaxy: https://galaxy.ansible.com/wtanaka/gcloud-sdk
