### ISSUE TITLE
Could you version this role? 

### ISSUE THREAD

**Issue by 030** [wtanaka/ansible-role-gcloud-sdk#6]
Could you create releases?

**Comment by wtanaka** [comment]
@030 do you mean versions of the SDK as docker image tags, or versions in github as git tags?

**Comment by wtanaka** [comment]
If you meant the git tag, here you go:

https://github.com/wtanaka/ansible-role-gcloud-sdk/releases/tag/v1.0.0

Let me know if not.

**Comment by 030** [comment]
Thank you
